"""Freeze installed dependencies with artifact SHA-256 hashes from official PyPI.

Use the reviewed Python 3.14 environment after installing requirements.txt, or
requirements-dev.txt for --dev. --dev never modifies the runtime lock.
"""
from __future__ import annotations

import argparse
from concurrent.futures import ThreadPoolExecutor
import importlib.metadata as metadata
from pathlib import Path
import re
from urllib.parse import quote

import httpx
from packaging.markers import default_environment
from packaging.requirements import Requirement

if __package__:
    from .check_requirements import canonical_name, matching_pins, read_pins
else:
    from check_requirements import canonical_name, matching_pins, read_pins


ROOT = Path(__file__).resolve().parents[1]


def marker_environments():
    """Include Windows and Linux dependencies for the same Python version."""
    base = default_environment()
    return [base | values for values in (
        {"sys_platform": "win32", "os_name": "nt", "platform_system": "Windows", "platform_machine": "AMD64"},
        {"sys_platform": "linux", "os_name": "posix", "platform_system": "Linux", "platform_machine": "x86_64"},
    )]


def installed_graph(pins):
    pending = [Requirement(f"{name}=={version}") for name, version in pins.items()]
    packages, processed = {}, set()
    environments = marker_environments()
    while pending:
        requirement = pending.pop()
        name = canonical_name(requirement.name)
        try:
            dist = metadata.distribution(name)
        except metadata.PackageNotFoundError as error:
            raise RuntimeError(f"Install the reviewed dependency graph first; missing {name}") from error
        if not requirement.specifier.contains(dist.version, prereleases=True):
            raise RuntimeError(f"Installed {name}=={dist.version} does not satisfy {requirement}")
        packages[name] = dist.version
        context = (name, frozenset(requirement.extras))
        if context in processed:
            continue
        processed.add(context)
        for raw in dist.requires or []:
            child = Requirement(raw)
            if child.marker is None or any(
                child.marker.evaluate(environment | {"extra": extra})
                for environment in environments for extra in {""} | requirement.extras
            ):
                pending.append(child)
    return packages


def release(item):
    name, version = item
    with httpx.Client(timeout=30, follow_redirects=False) as client:
        response = client.get(f"https://pypi.org/pypi/{quote(name, safe='')}/{quote(version, safe='')}/json")
        response.raise_for_status()
    data = response.json()
    if canonical_name(data["info"]["name"]) != name or data["info"]["version"] != version:
        raise RuntimeError(f"PyPI release identity differs from requested {name}=={version}")
    hashes = sorted({file["digests"]["sha256"] for file in data["urls"] if not file.get("yanked")})
    if not hashes or any(not re.fullmatch(r"[0-9a-f]{64}", value) for value in hashes):
        raise RuntimeError(f"No valid approved release artifacts for {name}=={version}")
    return name + "==" + version + " \\\n" + "".join(
        "    --hash=sha256:" + value + (" \\\n" if index < len(hashes) - 1 else "\n")
        for index, value in enumerate(hashes)
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dev", action="store_true", help="generate development lock while preserving requirements.lock")
    args = parser.parse_args()
    runtime = read_pins(ROOT / "requirements.txt", locked=False)
    if args.dev:
        runtime_lock = read_pins(ROOT / "requirements.lock", locked=True)
        matching_pins(runtime, runtime_lock, "requirements.txt")
        direct = read_pins(ROOT / "requirements-dev.txt", locked=False, include="requirements.txt")
        graph = installed_graph(direct)
        for name in graph.keys() & runtime_lock.keys():
            if graph[name] != runtime_lock[name]:
                raise RuntimeError(f"Installed {name} differs from requirements.lock; install the reviewed runtime lock first")
        packages = {name: version for name, version in graph.items() if name not in runtime_lock}
        output, label = ROOT / "requirements-dev.lock", "development"
        prefix = "# Generated by tools/lock_requirements.py --dev from the installed Python 3.14 development graph.\n"
        prefix += "# Release artifact hashes from official PyPI metadata are verified by pip in CI.\n-r requirements.lock\n"
    else:
        packages = installed_graph(runtime)
        output, label = ROOT / "requirements.lock", "runtime"
        prefix = "# Generated by tools/lock_requirements.py from the installed Python 3.14 runtime graph.\n"
        prefix += "# Release artifact hashes from official PyPI metadata are verified by pip at build.\n"
    with ThreadPoolExecutor(max_workers=6) as pool:
        entries = list(pool.map(release, sorted(packages.items())))
    temporary = output.with_suffix(output.suffix + ".tmp")
    temporary.write_text(prefix + "".join(entries), encoding="utf-8", newline="\n")
    temporary.replace(output)
    print(f"Locked {len(entries)} {label} packages with release artifact hashes.")


if __name__ == "__main__":
    main()
